baseURL = 'https://blog.omatheusmesmo.dev/'
canonifyURLs = false
relativeURLs = true
title = 'Matheus Oliveira'
theme = 'PaperMod'
defaultContentLanguage = 'pt'

# Asset Optimization
[minify]
  disableXML = false
  minifyOutput = true

[params]
  disqusShortname = 'blog-omatheusmesmo-dev'
  env = "production"
  title = "Matheus Oliveira"
  description = "Um blog dedicado a compartilhar conhecimentos e experiÃªncias em desenvolvimento de software, com foco em Java, seu ecossistema, Angular e Cloud."
  author = "Me"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullWidth = false
  displayFullLangName = true
  images = ["/images/duke.svg"]
  
  # Asset fingerprinting
  [params.assets]
    disableFingerprinting = false
    favicon = "/images/duke.svg"
    favicon16x16 = "/images/duke.svg"
    favicon32x32 = "/images/duke.svg"
    apple_touch_icon = "/images/duke.svg"

  # Disqus comments
  [params.comments]
    enabled = true

[languages]
  [languages.pt]
    languageCode = "pt-br"
    languageName = "ðŸ‡§ðŸ‡· PortugÃªs"
    weight = 1
    title = "Matheus Oliveira"
    [languages.pt.params]
      description = "Um blog dedicado a compartilhar conhecimentos e experiÃªncias em desenvolvimento de software, com foco em Java, seu ecossistema, Angular e Cloud."
      [languages.pt.params.homeInfoParams]
        Title = "Bem-vindo ao meu blog! ðŸ‘‹"
        Content = "Oi, eu sou o Matheus Oliveira. Sou desenvolvedor focado em Java, Quarkus e Cloud. Aqui compartilho guias tÃ©cnicos e experiÃªncias do meu dia a dia."
    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/about/"
        weight = 5
      [[languages.pt.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10
      [[languages.pt.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20
      
  [languages.en]
    languageCode = "en-us"
    languageName = "ðŸ‡ºðŸ‡¸ English"
    weight = 2
    title = "Matheus Oliveira"
    [languages.en.params]
      description = "A blog dedicated to sharing knowledge and experiences in software development, focusing on Java, its ecosystem, Angular, and Cloud."
      [languages.en.params.homeInfoParams]
        Title = "Welcome to my blog! ðŸ‘‹"
        Content = "Hi, I'm Matheus Oliveira. I'm a developer focused on Java, Quarkus, and Cloud. Here I share technical guides and experiences from my daily life."
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20

[permalinks]
  posts = "/:year/:month/:slug/"
